**Análise de Dados - COVID 19**

In [ ]:
#1) Alterar a exclusão das colunas do dataset antes de correlacionar por algoritmo sem informar a coluna manualmente;

#2) Mapa de Calor após retirada de novas colunas do dataset

#3) Inferência dos Valores de Resultado - estudar melhor

#4) Realizar Dados categóricos para numéricos utilizando pandas get_dummies

#5) Criar modelo de Regressão Linear - PENDENTE

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#!pip install openpyxl==3.0.0

In [ ]:
dataset = pd.read_excel('Planilha COVID-19 completa.xlsx', header=1)

In [ ]:
dataset.shape

(685, 188)

In [ ]:
dataset.head(5)

ORIGEM DA AMOSTRA Nº INTERNO       Data da coleta Classif. OMS  \
0            UTI HU         01  2020-08-08 00:00:00        GRAVE   
1            UTI HU         02  2020-08-11 00:00:00        OBITO   
2            UTI HU         03  2020-08-12 00:00:00        OBITO   
3            UTI HU         04  2020-08-12 00:00:00        OBITO   
4            UTI HU         06  2020-08-13 00:00:00        OBITO   

  Classif. OMS modif. Classif. NIH Classif. Guideline (7th ed.)  \
0               GRAVE      CRITICO                      CRITICO   
1               GRAVE      CRITICO                      CRITICO   
2               GRAVE      CRITICO                      CRITICO   
3               GRAVE      CRITICO                      CRITICO   
4               GRAVE      CRITICO                      CRITICO   

       Data Nascimento  Idade (anos)       Sexo Ocupação  \
0  1965-08-18 00:00:00          55.0   FEMININO    99999   
1  1952-05-20 00:00:00          68.0  MASCULINO    99999   
2  1959-12-15 00:00:00          60.0   FEMININO    99999   
3  1943-05-08 00:00:00          77.0  MASCULINO    99999   
4  1991-12-06 00:00:00          28.0  MASCULINO    99999   

                    Escolaridade Raça/Cor Tipo Sanguíneo  \
0  ENSINO FUNDAMENTAL INCOMPLETO    PARDA          99999   
1                          99999    PARDA          99999   
2                          99999    PARDA          99999   
3  ENSINO FUNDAMENTAL INCOMPLETO    PARDA          99999   
4  ENSINO FUNDAMENTAL INCOMPLETO    PARDA          99999   

       Município de Residencia  Tempo de Internação (dias)  \
0  SANTA MARIA DA BOA VISTA-PE                        15.0   
1                 PETROLINA-PE                        32.0   
2                 PETROLINA-PE                        19.0   
3                 PETROLINA-PE                         5.0   
4                 PETROLINA-PE                        22.0   

  Semana Epidemiológica Data início dos sintomas      Data internação Febre  \
0               29/2020      2020-07-13 00:00:00  2020-07-24 00:00:00   SIM   
1               28/2020      2020-07-05 00:00:00  2020-07-14 00:00:00   SIM   
2               31/2020      2020-07-28 00:00:00  2020-08-06 00:00:00   SIM   
3               31/2020      2020-07-30 00:00:00  2020-08-08 00:00:00   SIM   
4               31/2020      2020-08-01 00:00:00  2020-08-09 00:00:00   SIM   

  Dor de garganta Tosse seca Tosse produtiva  \
0             NAO        SIM             NAO   
1             NAO        NAO             SIM   
2             NAO        SIM             NAO   
3             SIM        NAO             NAO   
4             NAO        SIM             NAO   

  Dispnéia / Desconforto respiratório Astenia Cefaleia Saturação de O2 <95  \
0                                 SIM     SIM      SIM                 SIM   
1                                 SIM     NAO      NAO                 SIM   
2                                 SIM     NAO      SIM                 SIM   
3                                 SIM     SIM      NAO                 SIM   
4                                 SIM     NAO      NAO                 NAO   

  Mal estar geral Dor em articulações Dor muscular Dor abdominal Diarreia  \
0             NAO                 NAO          SIM           NAO      NAO   
1             NAO                 NAO          NAO           NAO      NAO   
2             NAO                 NAO          SIM           NAO      SIM   
3             NAO                 NAO          NAO           NAO      NAO   
4             NAO                 NAO          NAO           NAO      NAO   

  Vômitos Alteração do olfato e do paladar Coriza / Congestão Nasal  \
0     NAO                              NAO                      SIM   
1     NAO                              NAO                      NAO   
2     NAO                              NAO                      NAO   
3     NAO                              NAO                      NAO   
4     NAO                              NAO  

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
dataset.replace(99999, np.nan, inplace = True)
dataset.replace(99999.0, np.nan, inplace = True)

In [ ]:
#cria um dataset com campos e seus % de registros nulos
#dataset.isnull().sum()
teste = (dataset.isnull().sum()/dataset.shape[0]) * 100

In [ ]:
#Cria um dataframe do dataset teste de nulos
teste1 = pd.DataFrame(teste,columns=list('A'))

In [ ]:
teste1.head(10)

A
ORIGEM DA AMOSTRA             0.145985
Nº INTERNO                    0.145985
Data da coleta                0.291971
Classif. OMS                  3.941606
Classif. OMS modif.           4.233577
Classif. NIH                  5.693431
Classif. Guideline (7th ed.)  5.693431
Data Nascimento               0.291971
Idade (anos)                  0.437956
Sexo                          0.437956

In [ ]:
#reindexa o dataframe criado
teste1.reset_index(level=0, inplace=True)

In [ ]:
#visualiza o dataframe indexado
teste1.head(5)

index         A
0    ORIGEM DA AMOSTRA  0.145985
1           Nº INTERNO  0.145985
2       Data da coleta  0.291971
3         Classif. OMS  3.941606
4  Classif. OMS modif.  4.233577

In [ ]:
#Renomeia as Colunas do dataframe criado
teste1 = teste1.rename(columns={'index':'Campos','A': 'Valores'})

In [ ]:
teste1.columns

Index(['Campos', 'Valores'], dtype='object')

In [ ]:
#Visualiza dataframe com colunas renomeadas

#Desativa do pandas limites de linhas e colunas para exibição
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

#Carrega dados do dataframe
teste1.head(5)

Campos   Valores
0    ORIGEM DA AMOSTRA  0.145985
1           Nº INTERNO  0.145985
2       Data da coleta  0.291971
3         Classif. OMS  3.941606
4  Classif. OMS modif.  4.233577

In [ ]:
#Campos com mais de 30% nulos
teste1.loc[teste1['Valores']>30]

Campos    Valores
10                                        Ocupação  76.934307
11                                    Escolaridade  74.744526
12                                        Raça/Cor  45.985401
13                                  Tipo Sanguíneo  83.065693
38                                          Outros  55.620438
41                                              D2  87.445255
42                                         DATA D2  87.445255
43                                              D3  97.810219
44                                         DATA D3  97.664234
45                                Vacina influenza  69.781022
46                                  Data aplicação  83.795620
47                         Vacina antipneumocócica  78.102190
48                                Data aplicação.1  99.270073
49                                        Gravidez  63.941606
50                                        Puérpera  66.423358
71                                         Fumante  76.350365
72                                      Ex-fumante  76.350365
73                                  Outra condição  44.379562
80                                        FiO2 (%)  34.452555
81                                              PH  32.992701
82                                            PCO2  33.138686
83                                             PO2  31.678832
84                                             LAC  57.372263
85                                      HCO3 / BIC  48.321168
86                                       SATO2/SO2  46.569343
87                                  IO / REL / P/F  37.518248
88                              Principais achados  60.145985
90                  Infiltrado alveolar unilateral  53.284672
91                   Infiltrado alveolar bilateral  53.284672
92                         Infiltrado intersticial  53.284672
93                           Padrão de vidro fosco  53.138686
94                                     Pneumotórax  53.284672
95                                   Cardiomegalia  53.284672
96                                 Derrame pleural  53.284672
97                  Opacificação pulmonar completa  53.284672
99    Se sim, descrever qual a suplementação de O2  41.897810
101  Se sim, descrever qual o suporte ventilatório  64.087591
110                                       Outros.1  80.291971
113                            Neutrófilos (nº/μL)  55.766423
114                                Neutrófilos (%)  47.591241
115                                Linfócitos (nº)  47.737226
116                                 Linfócitos (%)  45.985401
117                                 Monócitos (n°)  66.861314
118                                  Monócitos (%)  66.569343
120               Razão neutrófilo-linfocito (RNL)  57.956204
121                 Razão monócito-linfócito (RML)  60.875912
122                                           TTPA  38.394161
123                                      D- Dímero  52.554745
124                                Albumina (g/dL)  72.408759
125                                      TGO (U/L)  32.846715
127                      BILIRRUBINA TOTAL (MG/DL)  31.386861
128                     BILIRRUBINA DIRETA (MG/DL)  51.970803
129                   BILIRRUBINA INDIRETA (MG/DL)  60.875912
131                                   CKMB (NG/ML)  75.328467
132                                      LDH (U/L)  75.182482
133             Veloc de eritrossedimentação (VHS)  98.248175
134                               Ferritina (ug/L)  42.627737
136                               TROPONINA T (MC)  59.562044
137                              TROPONINA I (UTI)  75.182482
139                TEMPO DE PROTROMBINA (segundos)  50.072993
140                                            INR  34.452555
141                Gama Glutamil Transferase (GGT)  55.036496
143                       Data do resultado da PCR  81.459854
144                                Tipo de amostra  80.000000
145           

In [ ]:
#deleta do dataframe os campos com menos de 30% de nulos
#para retirar apenas os maiores de 30% do dataset
teste1.drop(teste1.loc[teste1['Valores']<30].index, inplace=True)

In [ ]:
#dataset.drop(['Ocupação','Escolaridade','Raça/Cor','Tipo Sanguíneo','Tempo de Internação (dias)','Outros','Data aplicação.1','Temp. máx (°C)','Pressão DIASTOLICA + baixa','F.R mais alta','F.C mais alta','Saturação O2 mais baixa','FiO2 (%)','PH','PCO2','PO2','LAC','HCO3 / BIC','SATO2/SO2','IO / REL / P/F','Glicemia (HGT)','Neutrófilos (nº/μL)','Neutrófilos (%)','Linfócitos (nº)','Linfócitos (%)','Monócitos (n°)','Monócitos (%)','Razão neutrófilo-linfocito (RNL)','Razão monócito-linfócito (RML)','TTPA', 'Albumina (g/dL)', 'TGO (U/L)', 'TGP', 'BILIRRUBINA TOTAL (MG/DL)','BILIRRUBINA DIRETA (MG/DL)', 'BILIRRUBINA INDIRETA (MG/DL)','Creatinina','CKMB (NG/ML)','LDH (U/L)','Proteína C reativa (mg/L)','TROPONINA T (MC)','UREIA (mg/dL)','INR','Gama Glutamil Transferase (GGT)','Cq_E','Cq_OR','Cq_N','Data do teste rápido','IgG','IgM','Resultado','Método','IgG.1','IgM.1','Anticorpos totais','Data','Resultado.1','DATA','RESULTADO','Broncodilatador','Outros (ex: Ivermectina)','APRESENTOU COMPLICAÇOES','SE SIM, QUAIS?','TOMOU VACINA COVID-19?','SE SIM, QUAL?','DATA 1ª DOSE','DATA 2ª DOSE','INFECCAO POS VACINA','Local do óbito','Município do óbito','Início dos sintomas - desfecho','internação - desfecho'], axis=1)#Deleta do dataset colunas 
for ind in teste1.index:
  dataset = dataset.drop(teste1['Campos'][ind], axis=1)

In [ ]:
#retirar os 9999 restantes por média ou norma

In [ ]:
dataset.head(2)

ORIGEM DA AMOSTRA Nº INTERNO Data da coleta Classif. OMS  \
0            UTI HU         01     2020-08-08        GRAVE   
1            UTI HU         02     2020-08-11        OBITO   

  Classif. OMS modif. Classif. NIH Classif. Guideline (7th ed.)  \
0               GRAVE      CRITICO                      CRITICO   
1               GRAVE      CRITICO                      CRITICO   

       Data Nascimento  Idade (anos)       Sexo      Município de Residencia  \
0  1965-08-18 00:00:00          55.0   FEMININO  SANTA MARIA DA BOA VISTA-PE   
1  1952-05-20 00:00:00          68.0  MASCULINO                 PETROLINA-PE   

   Tempo de Internação (dias) Semana Epidemiológica Data início dos sintomas  \
0                        15.0               29/2020      2020-07-13 00:00:00   
1                        32.0               28/2020      2020-07-05 00:00:00   

  Data internação Febre Dor de garganta Tosse seca Tosse produtiva  \
0      2020-07-24   SIM             NAO        SIM             NAO   
1      2020-07-14   SIM             NAO        NAO             SIM   

  Dispnéia / Desconforto respiratório Astenia Cefaleia Saturação de O2 <95  \
0                                 SIM     SIM      SIM                 SIM   
1                                 SIM     NAO      NAO                 SIM   

  Mal estar geral Dor em articulações Dor muscular Dor abdominal Diarreia  \
0             NAO                 NAO          SIM           NAO      NAO   
1             NAO                 NAO          NAO           NAO      NAO   

  Vômitos Alteração do olfato e do paladar Coriza / Congestão Nasal  \
0     NAO                              NAO                      SIM   
1     NAO                              NAO                      NAO   

  Aperto torácico Dor no corpo Nauseas  \
0             SIM          NAO     NAO   
1             SIM          NAO     NAO   

                                                  D1              DATA D1  \
0           PNEUMONIA VIRAL NAO ESPECIFICADA (J12.9)  2020-07-24 00:00:00   
1  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-07-14 00:00:00   

  Síndrome de Down Diabetes  HAS  HIV Doença cardíaca crônica  \
0              NAO      SIM  SIM  NAO                     NAO   
1              NAO      SIM  SIM  NAO                     NAO   

  Doença hepática crônica Doença renal crônica Doença hematológica crônica  \
0                     NAO                  NAO                         NAO   
1                     NAO                  NAO                         NAO   

  Neoplasia Pneumopatia crônica Asma DPOC Bronquiectasia DPID Tuberculose  \
0       NAO                 NAO  NAO  SIM            NAO  NAO         NAO   
1       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   

  Doença reumatológica Obesidade Uso de imunossupressor Doença congênita  \
0                  NAO       NAO                    NAO              NAO   
1                  NAO       NAO                    NAO              NAO   

  Desnutrição  Temp. máx (°C)  Pressão SISTOLICA + baixa   \
0         NAO            38.6                       103.0   
1         NAO            37.1                       111.0   

   Pressão DIASTOLICA + baixa  F.R mais alta  F.C mais alta  \
0                        57.0           28.0          102.0   
1                        55.0           22.0           85.0   

   Saturação O2 mais baixa Fez pelo menos um Rx/TC de tórax?  \
0                     90.0                               NaN   
1                     85.0                               SIM   

  Suplementação de O2 Suporte ventilatório Medicação vasopressora  \
0                 SIM                  SIM                    SIM   
1                 NAO                  SIM                    SIM   

  Diálise/hemodiálise Parada cardiorespiratório Sepsis Choque  \
0                 SIM                       NAO    NaN    NaN   
1                 NaN                       SIM    NaN    NaN   

  Falência miocár

In [ ]:
dataset.head(1)

ORIGEM DA AMOSTRA Nº INTERNO Data da coleta Classif. OMS  \
0            UTI HU         01     2020-08-08        GRAVE   

  Classif. OMS modif. Classif. NIH Classif. Guideline (7th ed.)  \
0               GRAVE      CRITICO                      CRITICO   

       Data Nascimento  Idade (anos)      Sexo      Município de Residencia  \
0  1965-08-18 00:00:00          55.0  FEMININO  SANTA MARIA DA BOA VISTA-PE   

   Tempo de Internação (dias) Semana Epidemiológica Data início dos sintomas  \
0                        15.0               29/2020      2020-07-13 00:00:00   

  Data internação Febre Dor de garganta Tosse seca Tosse produtiva  \
0      2020-07-24   SIM             NAO        SIM             NAO   

  Dispnéia / Desconforto respiratório Astenia Cefaleia Saturação de O2 <95  \
0                                 SIM     SIM      SIM                 SIM   

  Mal estar geral Dor em articulações Dor muscular Dor abdominal Diarreia  \
0             NAO                 NAO          SIM           NAO      NAO   

  Vômitos Alteração do olfato e do paladar Coriza / Congestão Nasal  \
0     NAO                              NAO                      SIM   

  Aperto torácico Dor no corpo Nauseas  \
0             SIM          NAO     NAO   

                                         D1              DATA D1  \
0  PNEUMONIA VIRAL NAO ESPECIFICADA (J12.9)  2020-07-24 00:00:00   

  Síndrome de Down Diabetes  HAS  HIV Doença cardíaca crônica  \
0              NAO      SIM  SIM  NAO                     NAO   

  Doença hepática crônica Doença renal crônica Doença hematológica crônica  \
0                     NAO                  NAO                         NAO   

  Neoplasia Pneumopatia crônica Asma DPOC Bronquiectasia DPID Tuberculose  \
0       NAO                 NAO  NAO  SIM            NAO  NAO         NAO   

  Doença reumatológica Obesidade Uso de imunossupressor Doença congênita  \
0                  NAO       NAO                    NAO              NAO   

  Desnutrição  Temp. máx (°C)  Pressão SISTOLICA + baixa   \
0         NAO            38.6                       103.0   

   Pressão DIASTOLICA + baixa  F.R mais alta  F.C mais alta  \
0                        57.0           28.0          102.0   

   Saturação O2 mais baixa Fez pelo menos um Rx/TC de tórax?  \
0                     90.0                               NaN   

  Suplementação de O2 Suporte ventilatório Medicação vasopressora  \
0                 SIM                  SIM                    SIM   

  Diálise/hemodiálise Parada cardiorespiratório Sepsis Choque  \
0                 SIM                       NAO    NaN    NaN   

  Falência miocárdica Infarto miocárdio Insuficiência renal  Glicemia (HGT)  \
0                 NaN               NaN                 SIM             NaN   

   Leucócitos totais (/μL)   Plaquetas   TGP  Creatinina  \
0                  14080.0    238000.0  35.7         0.5   

   Proteína C reativa (mg/L)  UREIA (mg/dL) Realizou PCR?  \
0                       13.8           37.9           SIM   

  Realizou Teste Rápido (ANTICORPO)? Realizou Exame Sorológico?  \
0                                NAO                        NAO   

  Realizou Teste de Pesquisa de Antígeno (SWAB RÁPIDO)?  \
0                                                NAO      

  Foi administrado algum antiviral ou antibiótico na internação?  \
0                                                SIM               

                 Antibiótico Antiviral (Oseltamivir)  \
0  CEFTRIAXONA, AZITROMICINA             OSELTAMIVIR   

  Anticoagulante (Enoxaparina ou Análogo)         Broncodilatador  \
0                   ENOXAPARINA, HEPARINA  BROMETO DE IPRATROPIO    

  Cloroquina / Hidroxicloroquina Corticoterapia SRAG    Desfecho  \
0                            NAO   DEXAMETASONA  SIM  RECUPERADO   

      Data do Desfecho  Início dos sintomas - desfecho  internação - desfecho  
0  2020-08-09 00:00:00                            27.0                   16.0

In [ ]:
dataset.dropna(inplace=True)

In [ ]:
dataset.describe().round(2)

Idade (anos)  Tempo de Internação (dias)  Temp. máx (°C)  \
count        246.00                      246.00          246.00   
mean          51.41                        7.91           37.38   
std           14.20                        8.73            1.08   
min           20.00                        1.00           34.00   
25%           41.00                        3.00           36.60   
50%           51.00                        5.00           37.40   
75%           61.00                        9.00           38.18   
max           86.00                       52.00           40.00   

       Pressão SISTOLICA + baixa   Pressão DIASTOLICA + baixa  F.R mais alta  \
count                      246.00                      246.00         246.00   
mean                       102.87                       63.41          28.38   
std                         15.46                       12.74           7.52   
min                         44.00                       10.00          16.00   
25%                         94.00                       60.00          23.00   
50%                        100.00                       60.00          26.00   
75%                        110.00                       70.00          32.00   
max                        144.00                       98.00          63.00   

       F.C mais alta  Saturação O2 mais baixa  Glicemia (HGT)  \
count         246.00                   246.00          246.00   
mean          108.44                    89.28          166.38   
std            31.58                     5.44           69.28   
min            55.00                    53.00           63.00   
25%            92.25                    88.00          118.00   
50%           101.50                    90.00          144.00   
75%           117.75                    93.00          195.00   
max           443.00                    99.00          384.00   

       Leucócitos totais (/μL)   Plaquetas     TGP  Creatinina  \
count                   246.00      246.00  246.00      246.00   
mean                   9922.28   249493.90   53.45        0.90   
std                   11973.84    98629.68   43.44        0.59   
min                     420.00     8500.00    6.00        0.30   
25%                    5712.50   176750.00   23.92        0.64   
50%                    7750.00   230500.00   40.85        0.80   
75%                   10537.50   307000.00   70.12        1.00   
max                  140000.00   586000.00  290.00        6.50   

       Proteína C reativa (mg/L)  UREIA (mg/dL)  \
count                     246.00         246.00   
mean                      112.20          33.87   
std                        92.75          22.05   
min                         0.33          10.30   
25%                        41.75          21.60   
50%                        87.64          29.60   
75%                       161.57          38.00   
max                       405.00         204.80   

       Início dos sintomas - desfecho  internação - desfecho  
count                          246.00                 246.00  
mean                            17.13                   8.23  
std                             10.16                   9.24  
min                              5.00                   0.00  
25%                             11.00                   3.00  
50%                             14.00                   5.00  
75%                             19.00                   9.00  
max                             61.00                  52.00

In [ ]:
#Quais Colunas fazem sentido, retirar as demais
#Mapa de Calor após retirada de novas colunas
#Inferencia dos Valores de Resultado
#Dados categoricos para numericos utlizando pandas get_dummies (Exemplo o Sexo utilizar 0 ou 1 e outros campos com Sim ou Não)
#Criar modelo de Regressão Linear
#https://plotly.com/python/heatmaps/
#https://stackoverflow.com/questions/66572672/correlation-heatmap-in-plotly
dataset.corr().round(2)

Idade (anos)  Tempo de Internação (dias)  \
Idade (anos)                            1.00                        0.13   
Tempo de Internação (dias)              0.13                        1.00   
Temp. máx (°C)                         -0.01                        0.44   
Pressão SISTOLICA + baixa              -0.06                       -0.37   
Pressão DIASTOLICA + baixa             -0.09                       -0.34   
F.R mais alta                          -0.06                        0.44   
F.C mais alta                          -0.02                        0.44   
Saturação O2 mais baixa                -0.11                       -0.39   
Glicemia (HGT)                          0.17                        0.09   
Leucócitos totais (/μL)                -0.09                        0.03   
 Plaquetas                             -0.06                        0.09   
TGP                                    -0.09                       -0.10   
Creatinina                              0.06                        0.11   
Proteína C reativa (mg/L)               0.05                        0.14   
UREIA (mg/dL)                           0.29                        0.27   
Início dos sintomas - desfecho          0.17                        0.83   
internação - desfecho                   0.14                        0.91   

                                Temp. máx (°C)  Pressão SISTOLICA + baixa   \
Idade (anos)                             -0.01                       -0.06   
Tempo de Internação (dias)                0.44                       -0.37   
Temp. máx (°C)                            1.00                       -0.39   
Pressão SISTOLICA + baixa                -0.39                        1.00   
Pressão DIASTOLICA + baixa               -0.35                        0.68   
F.R mais alta                             0.41                       -0.30   
F.C mais alta                             0.46                       -0.37   
Saturação O2 mais baixa                  -0.33                        0.32   
Glicemia (HGT)                           -0.04                        0.06   
Leucócitos totais (/μL)                  -0.01                        0.01   
 Plaquetas                               -0.01                       -0.09   
TGP                                      -0.01                       -0.02   
Creatinina                                0.16                       -0.10   
Proteína C reativa (mg/L)                 0.23                       -0.02   
UREIA (mg/dL)                             0.23                       -0.21   
Início dos sintomas - desfecho            0.35                       -0.31   
internação - desfecho                     0.39                       -0.31   

                                Pressão DIASTOLICA + baixa  F.R mais alta  \
Idade (anos)                                         -0.09          -0.06   
Tempo de Internação (dias)                           -0.34           0.44   
Temp. máx (°C)                                       -0.35           0.41   
Pressão SISTOLICA + baixa                             0.68          -0.30   
Pressão DIASTOLICA + baixa                            1.00          -0.25   
F.R mais alta                                        -0.25           1.00   
F.C mais alta                                        -0.30           0.41   
Saturação O2 mais baixa                               0.31          -0.38   
Glicemia (HGT)                                       -0.00           0.04   
Leucócitos totais (/μL)                               0.03           0.05   
 Plaquetas                                           -0.00           0.24   
TGP                                                  -0.02           0.01   
Creatinina                                           -0.08           0.13   
Proteína C reativa (mg/L)                            -0.04           0.22   
UREIA (mg/dL)                                        -0.18           0.17   
Início dos sintomas - desf

In [ ]:
#após a correlacao precisamos salvar o dataset em novo arquivo
dataset2 = pd.DataFrame(dataset)

In [ ]:
dataset2.to_csv('nome_do_arquivo.csv')

In [ ]:
dataset3 = pd.read_csv('nome_do_arquivo.csv',encoding='utf-8')

In [ ]:
dataset3.head(2)

Unnamed: 0 ORIGEM DA AMOSTRA  Nº INTERNO Data da coleta Classif. OMS  \
0          47     MONTE CARMELO  60 / A1887     2020-11-26     MODERADO   
1          49     MONTE CARMELO          66     2020-11-30     MODERADO   

  Classif. OMS modif. Classif. NIH Classif. Guideline (7th ed.)  \
0            MODERADO        GRAVE                     MODERADO   
1            MODERADO        GRAVE                     MODERADO   

       Data Nascimento  Idade (anos)       Sexo Município de Residencia  \
0  1960-12-30 00:00:00          60.0  MASCULINO            PETROLINA-PE   
1  1972-06-02 00:00:00          48.0  MASCULINO            PETROLINA-PE   

   Tempo de Internação (dias) Semana Epidemiológica Data início dos sintomas  \
0                         2.0               46/2020      2020-11-14 00:00:00   
1                         7.0               48/2020      2020-11-23 00:00:00   

  Data internação Febre Dor de garganta Tosse seca Tosse produtiva  \
0      2020-11-25   SIM             NAO        SIM             SIM   
1      2020-11-30   NAO             NAO        SIM             NAO   

  Dispnéia / Desconforto respiratório Astenia Cefaleia Saturação de O2 <95  \
0                                 SIM     NAO      SIM                 NAO   
1                                 SIM     NAO      NAO                 SIM   

  Mal estar geral Dor em articulações Dor muscular Dor abdominal Diarreia  \
0             SIM                 NAO          SIM           NAO      NAO   
1             NAO                 NAO          NAO           NAO      NAO   

  Vômitos Alteração do olfato e do paladar Coriza / Congestão Nasal  \
0     NAO                              SIM                      SIM   
1     NAO                              SIM                      NAO   

  Aperto torácico Dor no corpo Nauseas  \
0             NAO          NAO     NAO   
1             NAO          NAO     NAO   

                                                  D1              DATA D1  \
0  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-25 00:00:00   
1  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-30 00:00:00   

  Síndrome de Down Diabetes  HAS  HIV Doença cardíaca crônica  \
0              NAO      SIM  SIM  NAO                     NAO   
1              NAO      NAO  SIM  NAO                     NAO   

  Doença hepática crônica Doença renal crônica Doença hematológica crônica  \
0                     NAO                  NAO                         NAO   
1                     NAO                  NAO                         NAO   

  Neoplasia Pneumopatia crônica Asma DPOC Bronquiectasia DPID Tuberculose  \
0       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   
1       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   

  Doença reumatológica Obesidade Uso de imunossupressor Doença congênita  \
0                  NAO       NAO                    NAO              NAO   
1                  NAO       SIM                    NAO              NAO   

  Desnutrição  Temp. máx (°C)  Pressão SISTOLICA + baixa   \
0         NAO            36.9                       110.0   
1         NAO            36.6                       110.0   

   Pressão DIASTOLICA + baixa  F.R mais alta  F.C mais alta  \
0                        70.0           28.0           76.0   
1                        60.0           26.0           96.0   

   Saturação O2 mais baixa Fez pelo menos um Rx/TC de tórax?  \
0                     91.0                               NAO   
1                     88.0                               NAO   

  Suplementação de O2 Suporte ventilatório Medicação vasopressora  \
0                 SIM                  NAO                    NAO   
1                 SIM                  NAO                    NAO   

  Diálise/hemodiálise Parada cardiorespiratório Sepsis Choque  \
0                 NAO                       NAO    NAO    NAO   
1                 NAO                       NAO    NAO    NA

In [ ]:
dataset3 = dataset3[['Unnamed: 0',
 'ORIGEM DA AMOSTRA',
 'Nº INTERNO',
 'Data da coleta',
 'Classif. OMS modif.',
 'Classif. NIH',
 'Classif. Guideline (7th ed.)',
 'Data Nascimento',
 'Idade (anos)',
 'Sexo',
 'Município de Residencia',
 'Tempo de Internação (dias)',
 'Semana Epidemiológica',
 'Data início dos sintomas',
 'Data internação',
 'Febre',
 'Dor de garganta',
 'Tosse seca',
 'Tosse produtiva',
 'Dispnéia / Desconforto respiratório',
 'Astenia',
 'Cefaleia',
 'Saturação de O2 <95',
 'Mal estar geral',
 'Dor em articulações',
 'Dor muscular',
 'Dor abdominal',
 'Diarreia',
 'Vômitos',
 'Alteração do olfato e do paladar',
 'Coriza / Congestão Nasal',
 'Aperto torácico',
 'Dor no corpo',
 'Nauseas',
 'D1',
 'DATA D1',
 'Síndrome de Down',
 'Diabetes',
 'HAS',
 'HIV',
 'Doença cardíaca crônica',
 'Doença hepática crônica',
 'Doença renal crônica',
 'Doença hematológica crônica',
 'Neoplasia',
 'Pneumopatia crônica',
 'Asma',
 'DPOC',
 'Bronquiectasia',
 'DPID',
 'Tuberculose',
 'Doença reumatológica',
 'Obesidade',
 'Uso de imunossupressor',
 'Doença congênita',
 'Desnutrição',
 'Temp. máx (°C)',
 'Pressão SISTOLICA + baixa ',
 'Pressão DIASTOLICA + baixa',
 'F.R mais alta',
 'F.C mais alta',
 'Saturação O2 mais baixa',
 'Fez pelo menos um Rx/TC de tórax?',
 'Suplementação de O2',
 'Suporte ventilatório',
 'Medicação vasopressora',
 'Diálise/hemodiálise',
 'Parada cardiorespiratório',
 'Sepsis',
 'Choque',
 'Falência miocárdica',
 'Infarto miocárdio',
 'Insuficiência renal',
 'Glicemia (HGT)',
 'Leucócitos totais (/μL)',
 ' Plaquetas',
 'TGP',
 'Creatinina',
 'Proteína C reativa (mg/L)',
 'UREIA (mg/dL)',
 'Realizou PCR?',
 'Realizou Teste Rápido (ANTICORPO)?',
 'Realizou Exame Sorológico?',
 'Realizou Teste de Pesquisa de Antígeno (SWAB RÁPIDO)?',
 'Foi administrado algum antiviral ou antibiótico na internação?',
 'Antibiótico',
 'Antiviral (Oseltamivir)',
 'Anticoagulante (Enoxaparina ou Análogo)',
 'Broncodilatador',
 'Cloroquina / Hidroxicloroquina',
 'Corticoterapia',
 'SRAG',
 'Desfecho',
 'Data do Desfecho',
 'Início dos sintomas - desfecho',
 'internação - desfecho',
 'Classif. OMS']]

In [ ]:
dataset3.head(2)

Unnamed: 0 ORIGEM DA AMOSTRA  Nº INTERNO Data da coleta  \
0          47     MONTE CARMELO  60 / A1887     2020-11-26   
1          49     MONTE CARMELO          66     2020-11-30   

  Classif. OMS modif. Classif. NIH Classif. Guideline (7th ed.)  \
0            MODERADO        GRAVE                     MODERADO   
1            MODERADO        GRAVE                     MODERADO   

       Data Nascimento  Idade (anos)       Sexo Município de Residencia  \
0  1960-12-30 00:00:00          60.0  MASCULINO            PETROLINA-PE   
1  1972-06-02 00:00:00          48.0  MASCULINO            PETROLINA-PE   

   Tempo de Internação (dias) Semana Epidemiológica Data início dos sintomas  \
0                         2.0               46/2020      2020-11-14 00:00:00   
1                         7.0               48/2020      2020-11-23 00:00:00   

  Data internação Febre Dor de garganta Tosse seca Tosse produtiva  \
0      2020-11-25   SIM             NAO        SIM             SIM   
1      2020-11-30   NAO             NAO        SIM             NAO   

  Dispnéia / Desconforto respiratório Astenia Cefaleia Saturação de O2 <95  \
0                                 SIM     NAO      SIM                 NAO   
1                                 SIM     NAO      NAO                 SIM   

  Mal estar geral Dor em articulações Dor muscular Dor abdominal Diarreia  \
0             SIM                 NAO          SIM           NAO      NAO   
1             NAO                 NAO          NAO           NAO      NAO   

  Vômitos Alteração do olfato e do paladar Coriza / Congestão Nasal  \
0     NAO                              SIM                      SIM   
1     NAO                              SIM                      NAO   

  Aperto torácico Dor no corpo Nauseas  \
0             NAO          NAO     NAO   
1             NAO          NAO     NAO   

                                                  D1              DATA D1  \
0  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-25 00:00:00   
1  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-30 00:00:00   

  Síndrome de Down Diabetes  HAS  HIV Doença cardíaca crônica  \
0              NAO      SIM  SIM  NAO                     NAO   
1              NAO      NAO  SIM  NAO                     NAO   

  Doença hepática crônica Doença renal crônica Doença hematológica crônica  \
0                     NAO                  NAO                         NAO   
1                     NAO                  NAO                         NAO   

  Neoplasia Pneumopatia crônica Asma DPOC Bronquiectasia DPID Tuberculose  \
0       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   
1       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   

  Doença reumatológica Obesidade Uso de imunossupressor Doença congênita  \
0                  NAO       NAO                    NAO              NAO   
1                  NAO       SIM                    NAO              NAO   

  Desnutrição  Temp. máx (°C)  Pressão SISTOLICA + baixa   \
0         NAO            36.9                       110.0   
1         NAO            36.6                       110.0   

   Pressão DIASTOLICA + baixa  F.R mais alta  F.C mais alta  \
0                        70.0           28.0           76.0   
1                        60.0           26.0           96.0   

   Saturação O2 mais baixa Fez pelo menos um Rx/TC de tórax?  \
0                     91.0                               NAO   
1                     88.0                               NAO   

  Suplementação de O2 Suporte ventilatório Medicação vasopressora  \
0                 SIM                  NAO                    NAO   
1                 SIM                  NAO                    NAO   

  Diálise/hemodiálise Parada cardiorespiratório Sepsis Choque  \
0                 NAO                       NAO    NAO    NAO   
1                 NAO                       NAO    NAO    NAO   

  Falência miocárdica Infarto mio

In [ ]:
dataset3.shape

(246, 97)

In [ ]:
dataset3.head(2)

Unnamed: 0 ORIGEM DA AMOSTRA  Nº INTERNO Data da coleta  \
0          47     MONTE CARMELO  60 / A1887     2020-11-26   
1          49     MONTE CARMELO          66     2020-11-30   

  Classif. OMS modif. Classif. NIH Classif. Guideline (7th ed.)  \
0            MODERADO        GRAVE                     MODERADO   
1            MODERADO        GRAVE                     MODERADO   

       Data Nascimento  Idade (anos)       Sexo Município de Residencia  \
0  1960-12-30 00:00:00          60.0  MASCULINO            PETROLINA-PE   
1  1972-06-02 00:00:00          48.0  MASCULINO            PETROLINA-PE   

   Tempo de Internação (dias) Semana Epidemiológica Data início dos sintomas  \
0                         2.0               46/2020      2020-11-14 00:00:00   
1                         7.0               48/2020      2020-11-23 00:00:00   

  Data internação Febre Dor de garganta Tosse seca Tosse produtiva  \
0      2020-11-25   SIM             NAO        SIM             SIM   
1      2020-11-30   NAO             NAO        SIM             NAO   

  Dispnéia / Desconforto respiratório Astenia Cefaleia Saturação de O2 <95  \
0                                 SIM     NAO      SIM                 NAO   
1                                 SIM     NAO      NAO                 SIM   

  Mal estar geral Dor em articulações Dor muscular Dor abdominal Diarreia  \
0             SIM                 NAO          SIM           NAO      NAO   
1             NAO                 NAO          NAO           NAO      NAO   

  Vômitos Alteração do olfato e do paladar Coriza / Congestão Nasal  \
0     NAO                              SIM                      SIM   
1     NAO                              SIM                      NAO   

  Aperto torácico Dor no corpo Nauseas  \
0             NAO          NAO     NAO   
1             NAO          NAO     NAO   

                                                  D1              DATA D1  \
0  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-25 00:00:00   
1  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-30 00:00:00   

  Síndrome de Down Diabetes  HAS  HIV Doença cardíaca crônica  \
0              NAO      SIM  SIM  NAO                     NAO   
1              NAO      NAO  SIM  NAO                     NAO   

  Doença hepática crônica Doença renal crônica Doença hematológica crônica  \
0                     NAO                  NAO                         NAO   
1                     NAO                  NAO                         NAO   

  Neoplasia Pneumopatia crônica Asma DPOC Bronquiectasia DPID Tuberculose  \
0       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   
1       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   

  Doença reumatológica Obesidade Uso de imunossupressor Doença congênita  \
0                  NAO       NAO                    NAO              NAO   
1                  NAO       SIM                    NAO              NAO   

  Desnutrição  Temp. máx (°C)  Pressão SISTOLICA + baixa   \
0         NAO            36.9                       110.0   
1         NAO            36.6                       110.0   

   Pressão DIASTOLICA + baixa  F.R mais alta  F.C mais alta  \
0                        70.0           28.0           76.0   
1                        60.0           26.0           96.0   

   Saturação O2 mais baixa Fez pelo menos um Rx/TC de tórax?  \
0                     91.0                               NAO   
1                     88.0                               NAO   

  Suplementação de O2 Suporte ventilatório Medicação vasopressora  \
0                 SIM                  NAO                    NAO   
1                 SIM                  NAO                    NAO   

  Diálise/hemodiálise Parada cardiorespiratório Sepsis Choque  \
0                 NAO                       NAO    NAO    NAO   
1                 NAO                       NAO    NAO    NAO   

  Falência miocárdica Infarto mio

In [ ]:
#CountValues para colunes categoricas para mais de 1 valor
#Listar quais
#dataset3.drop(["ORIGEM DA AMOSTRA","Nº INTERNO","Data da coleta",'Classif. OMS modif.','Classif. NIH','Classif. Guideline (7th ed.)','Data Nascimento','Sexo','Município de Residencia','Semana Epidemiológica','Data início dos sintomas','Data internação','Febre','Dor de garganta','Tosse seca','Tosse produtiva','Dispnéia / Desconforto respiratório','Astenia','Cefaleia','Saturação de O2 <95','Mal estar geral','Dor em articulações','Dor muscular','Dor abdominal','Diarreia','Vômitos','Alteração do olfato e do paladar','Coriza / Congestão Nasal','Aperto torácico','Dor no corpo','Nauseas','D1','DATA D1','Síndrome de Down','Diabetes','HAS','HIV','Doença cardíaca crônica','Doença hepática crônica','Doença renal crônica','Doença hematológica crônica','Neoplasia','Pneumopatia crônica','Asma','DPOC','Bronquiectasia','DPID','Tuberculose','Doença reumatológica','Obesidade','Uso de imunossupressor','Doença congênita','Desnutrição','Fez pelo menos um Rx/TC de tórax?','Suplementação de O2','Suporte ventilatório','Medicação vasopressora','Diálise/hemodiálise','Parada cardiorespiratório','Sepsis','Choque','Falência miocárdica','Infarto miocárdio','Insuficiência renal','Realizou PCR?','Realizou Teste Rápido (ANTICORPO)?','Realizou Exame Sorológico?','Realizou Teste de Pesquisa de Antígeno (SWAB RÁPIDO)?','Foi administrado algum antiviral ou antibiótico na internação?','Antibiótico','Antiviral (Oseltamivir)','Anticoagulante (Enoxaparina ou Análogo)','Broncodilatador','Cloroquina / Hidroxicloroquina','Corticoterapia','SRAG','Desfecho','Data do Desfecho'],inplace = True, axis=1)

In [ ]:
dataset3.head(1)

Unnamed: 0 ORIGEM DA AMOSTRA  Nº INTERNO Data da coleta  \
0          47     MONTE CARMELO  60 / A1887     2020-11-26   

  Classif. OMS modif. Classif. NIH Classif. Guideline (7th ed.)  \
0            MODERADO        GRAVE                     MODERADO   

       Data Nascimento  Idade (anos)       Sexo Município de Residencia  \
0  1960-12-30 00:00:00          60.0  MASCULINO            PETROLINA-PE   

   Tempo de Internação (dias) Semana Epidemiológica Data início dos sintomas  \
0                         2.0               46/2020      2020-11-14 00:00:00   

  Data internação Febre Dor de garganta Tosse seca Tosse produtiva  \
0      2020-11-25   SIM             NAO        SIM             SIM   

  Dispnéia / Desconforto respiratório Astenia Cefaleia Saturação de O2 <95  \
0                                 SIM     NAO      SIM                 NAO   

  Mal estar geral Dor em articulações Dor muscular Dor abdominal Diarreia  \
0             SIM                 NAO          SIM           NAO      NAO   

  Vômitos Alteração do olfato e do paladar Coriza / Congestão Nasal  \
0     NAO                              SIM                      SIM   

  Aperto torácico Dor no corpo Nauseas  \
0             NAO          NAO     NAO   

                                                  D1              DATA D1  \
0  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-25 00:00:00   

  Síndrome de Down Diabetes  HAS  HIV Doença cardíaca crônica  \
0              NAO      SIM  SIM  NAO                     NAO   

  Doença hepática crônica Doença renal crônica Doença hematológica crônica  \
0                     NAO                  NAO                         NAO   

  Neoplasia Pneumopatia crônica Asma DPOC Bronquiectasia DPID Tuberculose  \
0       NAO                 NAO  NAO  NAO            NAO  NAO         NAO   

  Doença reumatológica Obesidade Uso de imunossupressor Doença congênita  \
0                  NAO       NAO                    NAO              NAO   

  Desnutrição  Temp. máx (°C)  Pressão SISTOLICA + baixa   \
0         NAO            36.9                       110.0   

   Pressão DIASTOLICA + baixa  F.R mais alta  F.C mais alta  \
0                        70.0           28.0           76.0   

   Saturação O2 mais baixa Fez pelo menos um Rx/TC de tórax?  \
0                     91.0                               NAO   

  Suplementação de O2 Suporte ventilatório Medicação vasopressora  \
0                 SIM                  NAO                    NAO   

  Diálise/hemodiálise Parada cardiorespiratório Sepsis Choque  \
0                 NAO                       NAO    NAO    NAO   

  Falência miocárdica Infarto miocárdio Insuficiência renal  Glicemia (HGT)  \
0                 NAO               NAO                 NAO           248.0   

   Leucócitos totais (/μL)   Plaquetas   TGP  Creatinina  \
0                  15090.0    233000.0  31.2        1.01   

   Proteína C reativa (mg/L)  UREIA (mg/dL) Realizou PCR?  \
0                      98.07           38.6           SIM   

  Realizou Teste Rápido (ANTICORPO)? Realizou Exame Sorológico?  \
0                                SIM                        NAO   

  Realizou Teste de Pesquisa de Antígeno (SWAB RÁPIDO)?  \
0                                                NAO      

  Foi administrado algum antiviral ou antibiótico na internação?  Antibiótico  \
0                                                SIM              CEFTRIAXONA   

  Antiviral (Oseltamivir) Anticoagulante (Enoxaparina ou Análogo)  \
0             OSELTAMIVIR                             ENOXAPARINA   

  Broncodilatador Cloroquina / Hidroxicloroquina Corticoterapia SRAG  \
0      SALBUTAMOL                            NAO   DEXAMETASONA  NAO   

     Desfecho     Data do Desfecho  Início dos sintomas - desfecho  \
0  RECUPERADO  2020-11-27 00:00:00                            13.0   

   internação - desfecho Classif. OMS  
0                    2.0     MODERADO

In [ ]:
#dataset3.drop(['Unnamed: 0',"ORIGEM DA AMOSTRA","Nº INTERNO","Data da coleta",'Classif. OMS modif.','Classif. NIH','Classif. Guideline (7th ed.)','Data Nascimento','Município de Residencia','Semana Epidemiológica','Data início dos sintomas','Data internação','D1','DATA D1','D2','DATA D2','D3','DATA D3','Data aplicação','Vacina antipneumocócica','Data aplicação.1','Outra condição','Principais achados','Fez pelo menos um Rx/TC de tórax?','Suplementação de O2','Se sim, descrever qual a suplementação de O2','Se sim, descrever qual o suporte ventilatório','Se sim, descrever qual o suporte ventilatório','Sepsis','Choque','Outros.1','Glicemia (HGT)','Data do resultado da PCR','Realizou PCR?','Tipo de amostra','Teste realizado','Interpretação','Tipo de prova','Realizou Teste Rápido (ANTICORPO)?','Realizou Exame Sorológico?','Data','Realizou Teste de Pesquisa de Antígeno (SWAB RÁPIDO)?','DATA','Foi administrado algum antiviral ou antibiótico na internação?','Antibiótico','Antiviral (Oseltamivir)','Anticoagulante (Enoxaparina ou Análogo)','Broncodilatador','Cloroquina / Hidroxicloroquina','Corticoterapia','SRAG','Desfecho','Data do Desfecho','Início dos sintomas - desfecho','internação - desfecho'],inplace = True, axis=1)

In [ ]:
dataset3.shape

(246, 97)

In [ ]:
#Features/Previsores e a Target/Classe
previsores = dataset3.iloc[:, 0:96].values # da primeira coluna a penultima
classe     = dataset3.iloc[:,96].values # Coluna Classif OMS

In [ ]:
previsores = pd.DataFrame(previsores)

In [ ]:
previsores.head(2)

0              1           2           3         4      5         6   \
0  47  MONTE CARMELO  60 / A1887  2020-11-26  MODERADO  GRAVE  MODERADO   
1  49  MONTE CARMELO          66  2020-11-30  MODERADO  GRAVE  MODERADO   

                    7     8          9             10   11       12  \
0  1960-12-30 00:00:00  60.0  MASCULINO  PETROLINA-PE  2.0  46/2020   
1  1972-06-02 00:00:00  48.0  MASCULINO  PETROLINA-PE  7.0  48/2020   

                    13          14   15   16   17   18   19   20   21   22  \
0  2020-11-14 00:00:00  2020-11-25  SIM  NAO  SIM  SIM  SIM  NAO  SIM  NAO   
1  2020-11-23 00:00:00  2020-11-30  NAO  NAO  SIM  NAO  SIM  NAO  NAO  SIM   

    23   24   25   26   27   28   29   30   31   32   33  \
0  SIM  NAO  SIM  NAO  NAO  NAO  SIM  SIM  NAO  NAO  NAO   
1  NAO  NAO  NAO  NAO  NAO  NAO  SIM  NAO  NAO  NAO  NAO   

                                                  34                   35  \
0  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-25 00:00:00   
1  INFECCAO POR CORONAVIRUS DE LOCALIZACAO NAO ES...  2020-11-30 00:00:00   

    36   37   38   39   40   41   42   43   44   45   46   47   48   49   50  \
0  NAO  SIM  SIM  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO   
1  NAO  NAO  SIM  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO   

    51   52   53   54   55    56     57    58    59    60    61   62   63  \
0  NAO  NAO  NAO  NAO  NAO  36.9  110.0  70.0  28.0  76.0  91.0  NAO  SIM   
1  NAO  SIM  NAO  NAO  NAO  36.6  110.0  60.0  26.0  96.0  88.0  NAO  SIM   

    64   65   66   67   68   69   70   71   72     73       74        75  \
0  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  248.0  15090.0  233000.0   
1  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  NAO  162.0   9430.0  155000.0   

     76    77     78    79   80   81   82   83   84            85  \
0  31.2  1.01  98.07  38.6  SIM  SIM  NAO  NAO  SIM   CEFTRIAXONA   
1  39.0  1.26   15.4  25.8  NAO  SIM  NAO  SIM  NAO  AZITROMCIINA   

            86           87          88   89            90   91          92  \
0  OSELTAMIVIR  ENOXAPARINA  SALBUTAMOL  NAO  DEXAMETASONA  NAO  RECUPERADO   
1          NAO  ENOXAPARINA  SALBUTAMOL  SIM  DEXAMETASONA  NAO  RECUPERADO   

                    93    94   95  
0  2020-11-27 00:00:00  13.0  2.0  
1  2020-12-07 00:00:00  14.0  7.0

In [ ]:
previsores = pd.get_dummies(previsores)


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [ ]:
#labelencoder = LabelEncoder()
#labelencoder.fit_transform(dataset3['Sexo'])

In [ ]:
#previsores[:,0] 

In [ ]:
#dataset3 = pd.get_dummies(dataset3)

In [ ]:
#Melhorar as colunar 
#quais retiradas e porque

In [ ]:
#previsores_treinamento fit_transform
#no teste usar previsores_teste apenas Fit depois do Fit_tranform
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

In [ ]:
# from sklearn.model_selection import train_test_split
# previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores,classe,test_size=0.30, random_state=0)

1) Validação Cruzada
2) Teste de Significância Estatística
3) Random Forest
4) Rede Neural

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, accuracy_score

modelLR = LogisticRegression(random_state=1)

# Aqui vou guardar as matrizes de confusão
conf_matrix_list_of_arrays = []

# Usar kfold para separar os índices de treino e de teste
kf = KFold(n_splits=10, random_state=10, shuffle=True)
# Guardar as precisões de 10 rodadas
precisao = []

# loop das 5 rodadas
for train_index, test_index in kf.split(previsores):
  #Separação em treino e teste
  X_train, X_test = previsores[train_index], previsores[test_index]
  y_train, y_test = classe[train_index], classe[test_index]
  # Treinar o modelo
  modelLR.fit(X_train, y_train)
  # Calcular a matriz de confusão
  conf_matrix = confusion_matrix(y_test,modelLR.predict(X_test))
  # Guardar a matriz de confusão
  conf_matrix_list_of_arrays.append(conf_matrix)
  # Guardar a precisão
  precisao.append( accuracy_score(y_test, modelLR.predict(X_test)) )

# imprimir o array de precisões
print(precisao)
# imprimir as matrizes de confusão (nesse caso estou imprimindo a matriz que o modelo teve a melhor acurácia)
print(conf_matrix_list_of_arrays[1])


[0.78, 0.673469387755102, 0.7755102040816326, 0.673469387755102, 0.7755102040816326]
[[ 8 11  0]
 [ 0 25  0]
 [ 5  0  0]]


In [ ]:
# tive que rotular o array classe para poder treinar a rede neural 
from sklearn.preprocessing import LabelBinarizer

train_y = classe
lb = LabelBinarizer()
lb.fit(train_y)
classe = lb.transform(train_y)

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, accuracy_score

# rede neural (nesse ponto tem que experimentar outras arquiteturas da rede #hidden_layer_sizes)
model = MLPRegressor(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(200,300,400,300,200), max_iter = 100000, random_state=1)

# Aqui vou guardar as matrizes de confusão
conf_matrix_list_of_arrays = []
# Usar kfold para separar os índices de treino e de teste
kf = KFold(n_splits=5, random_state=10, shuffle=True)
# Guardar as precisões de 5 rodadas
precisao = []

# loop das 5 rodadas
for train_index, test_index in kf.split(previsores):
  #Separação em treino e teste
  X_train, X_test = previsores[train_index], previsores[test_index]
  y_train, y_test = classe[train_index], classe[test_index]
  # Treinar o modelo
  model.fit(X_train, y_train)
  # Calcular a matriz de confusão
  conf_matrix = confusion_matrix(lb.inverse_transform(y_test),lb.inverse_transform(model.predict(X_test)))
  # Guardar a matriz de confusão
  conf_matrix_list_of_arrays.append(conf_matrix)
  # Guardar a precisão
  precisao.append( accuracy_score(lb.inverse_transform(y_test), lb.inverse_transform(model.predict(X_test))) )

# imprimir o array de precisões
print(precisao)
# imprimir as matrizes de confusão (nesse caso estou imprimindo a matriz que o modelo teve a melhor acurácia)
print(conf_matrix_list_of_arrays[1])

[0.64, 0.4897959183673469, 0.46938775510204084, 0.7142857142857143, 0.5102040816326531]
[[ 6 13  0]
 [ 7 18  0]
 [ 2  3  0]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, accuracy_score

# rede neural (nesse ponto tem que experimentar outras arquiteturas da rede #hidden_layer_sizes)
modelRF = RandomForestClassifier(max_depth=3, random_state=0) 

# Aqui vou guardar as matrizes de confusão
conf_matrix_list_of_arrays = []
# Usar kfold para separar os índices de treino e de teste
kf = KFold(n_splits=5, random_state=10, shuffle=True)
# Guardar as precisões de 5 rodadas
precisao = []

# loop das 5 rodadas
for train_index, test_index in kf.split(previsores):
  
  #Separação em treino e teste - separar 70% / 30%
  X_train, X_test = previsores[train_index], previsores[test_index]
  y_train, y_test = classe[train_index], classe[test_index]
  # Treinar o modelo
  modelRF.fit(X_train, y_train)
  
  
  # Calcular a matriz de confusão - retirar
  conf_matrix = confusion_matrix(lb.inverse_transform(y_test),lb.inverse_transform(modelRF.predict(X_test)))
  # Guardar a matriz de confusão
  
  conf_matrix_list_of_arrays.append(conf_matrix)
  # Guardar a precisão
  precisao.append( accuracy_score(lb.inverse_transform(y_test), lb.inverse_transform(modelRF.predict(X_test))) )

# imprimir o array de precisões - add demais metricas
print(precisao)

# imprimir as matrizes de confusão (nesse caso estou imprimindo a matriz que o modelo teve a melhor acurácia)
print(conf_matrix_list_of_arrays[1])

[0.8, 0.7346938775510204, 0.8163265306122449, 0.8163265306122449, 0.8163265306122449]
[[11  8  0]
 [ 0 25  0]
 [ 5  0  0]]


In [ ]:
#
from mlxtend.evaluate import paired_ttest_5x2cv

t, p = paired_ttest_5x2cv(estimator1=modelLR,estimator2=modelRF,X=previsores, y=lb.inverse_transform(classe))
alpha = 0.05

print('t statistic: %.3f' % t)
print('aplha ', alpha)
print('p value: %.3f' % p)

if p > alpha:
  print("Fail to reject null hypotesis")
else:
  print("Reject null hypotesis")

t statistic: -1.414
aplha  0.05
p value: 0.216
Fail to reject null hypotesis


# Nova seção

In [ ]:
print(confusion_matrix(classe_teste, previsoes))

[[15 13  0]
 [ 0 40  0]
 [ 5  1  0]]


In [ ]:
# from sklearn.metrics import confusion_matrix, accuracy_score
# precisao = accuracy_score(classe_teste, previsoes)
# matriz = confusion_matrix(classe_teste, previsoes)



In [ ]:
#Oversample - veremos na proxima reuniao
precisao
#f1, acuracio, precisao

[0.8,
 0.7346938775510204,
 0.8163265306122449,
 0.8163265306122449,
 0.8163265306122449]

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(classe_teste, previsoes))

              precision    recall  f1-score   support

       GRAVE       0.75      0.54      0.63        28
    MODERADO       0.74      1.00      0.85        40
       OBITO       0.00      0.00      0.00         6

    accuracy                           0.74        74
   macro avg       0.50      0.51      0.49        74
weighted avg       0.68      0.74      0.70        74



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_scores = classificador.predict_proba(previsores_teste)
print(y_scores)

[[9.39646078e-01 5.64313939e-02 3.92252792e-03]
 [7.93005464e-01 1.72685852e-01 3.43086841e-02]
 [6.64067376e-01 3.28072922e-01 7.85970177e-03]
 [4.24868092e-02 9.56573564e-01 9.39627101e-04]
 [2.04735753e-01 7.90727689e-01 4.53655767e-03]
 [2.04085379e-02 9.78860266e-01 7.31196002e-04]
 [8.30211216e-02 9.15358371e-01 1.62050730e-03]
 [4.88894936e-02 9.49271120e-01 1.83938613e-03]
 [2.50148388e-01 7.42610154e-01 7.24145773e-03]
 [9.37335828e-02 9.03482727e-01 2.78368986e-03]
 [1.32857723e-01 8.64847981e-01 2.29429541e-03]
 [1.00293851e-01 8.97287198e-01 2.41895121e-03]
 [8.82935673e-01 5.16885845e-02 6.53757422e-02]
 [3.17329262e-02 9.67370833e-01 8.96240961e-04]
 [1.99592041e-01 7.94791815e-01 5.61614484e-03]
 [1.53062394e-01 8.44707545e-01 2.23006089e-03]
 [8.54763299e-02 9.12207032e-01 2.31663800e-03]
 [1.09288264e-02 9.88433273e-01 6.37900905e-04]
 [8.35957847e-01 1.40761768e-01 2.32803849e-02]
 [3.69287090e-01 5.29141440e-01 1.01571470e-01]
 [3.43109528e-02 9.64584640e-01 1.104407

In [ ]:
# Tentativa de construir a curva ROC
from sklearn import metrics
fpr, tpr, _ = metrics.roc_curve(classe_teste, y_scores)
auc = metrics.roc_auc_score(classe_teste, y_scores)
plt.plot(fpr,tpr,label="data 1, auc="+str(auc))
plt.legend(loc=4)
plt.show()

ValueError: ignored

In [ ]:
# Tentativa de construir a curva ROC
from sklearn.metrics import roc_curve
from sklearn.metrics import confusion_matrix
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

fpr, tpr, thresholds = roc_curve(classe_teste, y_scores[::,1])

fig = plt.figure(figsize=(6,6))
plt.plot([0,1], [0,1], "k--")
#plt.plot(fpr, tpr)
plt.xlabel("Falso positivo")
plt.ylabel("Verdadeiro positivo")
plt.title("Curva ROC")
plt.show()

In [ ]:
# Tentativa de construir a curva ROC
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(classe_teste, y_scores[:,1])
print("AUC: " + str(auc))

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve

def plot_roc_curve(fper, tper):
    plt.plot(fper, tper, color='red', label='ROC')
    plt.plot([0, 1], [0, 1], color='green', linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic Curve')
    plt.legend()
    plt.show()
    
data_X, cls_lab = make_classification(n_samples=2100, n_classes=2, weights=[1,1], random_state=2)
train_X, test_X, train_y, test_y = train_test_split(data_X, cls_lab, test_size=0.5, random_state=2)

model =RandomForestClassifier()
model.fit(train_X, train_y)

prob = model.predict_proba(test_X)
prob = prob[:, 1]
fper, tper, thresholds = roc_curve(test_y, prob)
plot_roc_curve(fper, tper)

In [ ]:
#Mapa de Calor
import plotly.express as px

fig = px.imshow(matriz,labels={"x": "0 - Moderado, 1 - Grave, 2 - Óbito"}, title="Matriz de Confusão")

fig.show()

In [ ]:
previsoes

In [ ]:
classe_treinamento

In [ ]:
# Os dados que ele usou como teste em relação ao treinamento
classe_teste